In [29]:
import numpy as np
import math as mp
import cv2


def test_gaussian_kernel_2D(kernel):
    assert kernel.shape == (29, 29), "The kernel is not the correct size"

    # peak should be at center
    gt_kernel_crop = np.array(
        [
            [0.00324, 0.00334, 0.00337, 0.00334, 0.00324],
            [0.00334, 0.00344, 0.00348, 0.00344, 0.00334],
            [0.00337, 0.00348, 0.00351, 0.00348, 0.00337],
            [0.00334, 0.00344, 0.00348, 0.00344, 0.00334],
            [0.00324, 0.00334, 0.00337, 0.00334, 0.00324],
        ]
    )

    kernel_h, kernel_w = kernel.shape
    h_center = kernel_h // 2
    w_center = kernel_w // 2
    student_kernel_crop = kernel[
        h_center - 2 : h_center + 3, w_center - 2 : w_center + 3
    ]
    print(gt_kernel_crop)
    print(student_kernel_crop)
    
#     assert np.allclose(
#         gt_kernel_crop, student_kernel_crop, atol=1e-5
#     ), "Values dont match"
#     assert np.allclose(kernel.sum(), 1.0, atol=1e-3)
    

ksize = 29
sigma = 7
kernel = np.arange(ksize).reshape(ksize,1)
mean = mp.floor(ksize / 2)
sum = 0.0
# kernel = np.subtract(kernel , mean)
# kernel = np.power(kernel,2)
# kernel = np.divide(kernel,(2*(sigma*sigma)))
# kernel = np.exp(-kernel)
# kernel = np.divide(kernel,mp.sqrt(2*np.pi)*sigma)

kernel = np.divide(np.exp(-np.divide(np.power(np.subtract(kernel , mean),2),(2*mp.pow(sigma,2)))),mp.sqrt(2*np.pi)*sigma)
kernel2 = np.divide(np.exp(-np.divide(np.power(np.subtract(kernel , mean),2),(2*mp.pow(sigma,2)))),mp.sqrt(2*np.pi)*sigma)
kernel = np.matmul(kernel,np.transpose(kernel2))
kernel /= np.sum(kernel)
test_gaussian_kernel_2D(kernel)
#kernel = cv2.getGaussianKernel( 29, 7 )
#kernel.shape
# assert kernel.shape == (29, 1), "The kernel is not the correct size"
# kernel = kernel.squeeze()

# # peak should be at center
# gt_kernel_crop = np.array([0.05405, 0.05688, 0.05865, 0.05925, 0.05865, 0.05688, 0.05405])
# h_center = ksize // 2
# student_kernel_crop = kernel[h_center - 3 : h_center + 4]

# # assert np.allclose(gt_kernel_crop, student_kernel_crop, atol=1e-5), "Values dont match"
# print(gt_kernel_crop)
# print(student_kernel_crop)
# print(np.allclose(gt_kernel_crop, student_kernel_crop, atol=1e-5))
# assert np.allclose(kernel.sum(), 1, atol=1e-3), "Kernel doesnt sum to 1"


[[0.00324 0.00334 0.00337 0.00334 0.00324]
 [0.00334 0.00344 0.00348 0.00344 0.00334]
 [0.00337 0.00348 0.00351 0.00348 0.00337]
 [0.00334 0.00344 0.00348 0.00344 0.00334]
 [0.00324 0.00334 0.00337 0.00334 0.00324]]
[[0.00197353 0.00197449 0.00197481 0.00197449 0.00197353]
 [0.00203488 0.00203586 0.0020362  0.00203586 0.00203488]
 [0.00205575 0.00205674 0.00205708 0.00205674 0.00205575]
 [0.00203488 0.00203586 0.0020362  0.00203586 0.00203488]
 [0.00197353 0.00197449 0.00197481 0.00197449 0.00197353]]


In [13]:
import math as mp
import cv2
sigma = 1.0
W = 5
kernel3 = [[0 for x in range(W)] for y in range(W)] 
mean = W/2
sum = 0.0
for x in range(0,W): 
    for y in range(0,W):
        kernel3[x][y] = mp.exp(-0.5 * (mp.pow((x-mean)/sigma, 2.0) + mp.pow((y-mean)/sigma,2.0)) )/ (2 * mp.pi * sigma * sigma);
        sum += kernel3[x][y]

for x in range(0,W):
    for y in range(0,W):
        kernel3[x][y] /= sum
print(kernel3)
kernel3 = cv2.getGaussianKernel( 3, 2 )
print(kernel3)


[[0.00031945703354825666, 0.0023604859420860392, 0.00641646604270551, 0.00641646604270551, 0.0023604859420860392], [0.0023604859420860392, 0.01744176304681091, 0.04741162754643456, 0.04741162754643456, 0.01744176304681091], [0.00641646604270551, 0.04741162754643456, 0.12887816561714138, 0.12887816561714138, 0.04741162754643456], [0.00641646604270551, 0.04741162754643456, 0.12887816561714138, 0.12887816561714138, 0.04741162754643456], [0.0023604859420860392, 0.01744176304681091, 0.04741162754643456, 0.04741162754643456, 0.01744176304681091]]
[[0.31916777]
 [0.36166446]
 [0.31916777]]


In [8]:
import numpy as np
f = np.array([[10,  7,  4],
       [ 3,  2,  1]])
g = np.array([[-1,-1,0],[-1,0,-1]])
np.median(f*g, axis=(0,1))

-2.0

In [1]:
import numpy as np
from tensorflow import keras


model = keras.models.Sequential()



#here in the snippet below
#D = 5 (first parameter)
#Stride= (1,1) by default
model.add(keras.layers.Conv2D(5, kernel_size=3, activation='relu', input_shape=(32, 32, 3)))
model.summary()

ModuleNotFoundError: No module named 'tensorflow'